version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: Projecto-Final
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin**123
      POSTGRES_DB: projecto-3
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
